---
title: KumoML
email: matthias.fey@tu-dortmund.de
email_2: jiaxuan@cs.stanford.edu
description: PyG is the go-to library for Graph Neural Networks. We hope to support everything that you will need to build a graph machine learning pipeline.
black_logo_1x: "/assets/images/logo_pyg.png"
black_logo_2x: "/assets/images/logo_pyg@2x.png"
light_logo_1x: "/assets/images/logo_pyg.png"
light_logo_2x: "/assets/images/logo_pyg@2x.png"
#address_01: Moonshine St. 14/05 <br /> Light City, London
phone_number: "+00 (123) 456 78 90"
copyright_text: "© 2021 KumoML.  All rights reserved."
google_analytics:
  enable: false
  key: UA-664136761-1
social_accounts:
  title: Follow Us
  links:
  - url: "#"
    icon: jam jam-twitter
  - url: "#"
    icon: jam jam-facebook
  - url: "#"
    icon: jam jam-instagram
  - url: "#"
    icon: jam jam-vimeo
  - url: "#"
    icon: jam jam-youtube
external_links:
  title: Learn More
  links:
  - url: "https://github.com/rusty1s/pytorch_geometric"
    text: Github
  - url: "https://pytorch-geometric.readthedocs.io/en/latest/"
    text: Documentation
  - url: "https://torchgeometricco.slack.com/ssb/redirect"
    text: Join slack
#  - url: "#"
#    text: About Us
#  - url: "#"
#    text: Our Story
#  - url: "#"
#    text: Projects
#  - url: "#"
#    text: Pricing
#  - url: "#"
#    text: Features
#external_links_02:
#  title: Need Help?
#  links:
#  - url: "#"
#    text: Support
#  - url: "#"
#    text: Get Started
#  - url: "#"
#    text: Contact Us
#  - url: "#"
#    text: Terms of Use
#  - url: "#"
#    text: Privacy Policy
#external_links_03:
#  title: Company
#  links:
#  - url: "#"
#    text: Our Team
#  - url: "#"
#    text: Strategy
#  - url: "#"
#    text: Service
#  - url: "#"
#    text: Mission
#  - url: "#"
#    text: Process
footer_newsletter:
  title: Our Newsletter
  sub_title: Subscribe to our newsletter to get our news & deals delivered to your
    inbox!
  subscribe_button_text: Join
one_page_nav_settings:
  links:
  - text: Home
    url: "#home"
  - text: Services
    url: "#services"
  - text: Experiences
    url: "#experiences"
  - text: Portfolio
    url: "#portfolio"
  - text: Testimonials
    url: "#testimonials"
  - text: Contact
    url: "#contact"
author_page_header:
  header_background_image: "/assets/images/art/bg31.jpg"
gallery:
  images:
  - img: "/assets/images/art/z1.svg"
  - img: "/assets/images/art/z2.svg"
  - img: "/assets/images/art/z3.svg"
  - img: "/assets/images/art/z4.svg"
  - img: "/assets/images/art/z5.svg"
  - img: "/assets/images/art/z6.svg"
  - img: "/assets/images/art/z7.svg"
  - img: "/assets/images/art/z8.svg"
